# Generated by Django 5.2.7 on 2025-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='nomor induk kependudukan')),
                ('nama_lengkap', models.CharField(max_length=100, verbose_name='nama lengkap')),
                ('alamat', models.TextField(verbose_name='alamat tinggal')),
                ('no_telepon', models.CharField(blank=True, max_length=15, verbose_name='nomor telfon')),
                ('tanggal_registrasi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
