# Generated by Django 5.2.7 on 2025-10-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qarga',
            new_name='Warga',
        ),
    ]
